-- ALTER TABLE examples
ALTER TABLE users ADD COLUMN age INT;
ALTER TABLE products MODIFY category VARCHAR(100);

-- ADD CONSTRAINT
ALTER TABLE users ADD CONSTRAINT chk_age CHECK (age >= 18);

-- DROP COLUMN
ALTER TABLE users DROP COLUMN age;
